version: 2
jobs:
  develop-branch:
    docker:
      - image: circleci/openjdk:8u171-jdk
   
    steps:
      - checkout 
      - run: 
            name: Retrieve version number from POM
            comand: |
                mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec


  master-branch:
    docker:
      - image: circleci/openjdk:8-jdk
   
    steps:
      - checkout
      - run: 
            name: Retrieve version number from POM
            comand: |
                MVN_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
                echo MVN_VERSION
      - run: 
            name: build and deploy to development 
            command: |
              cd config
              sudo chmod 755 *.sh
              ./build_production.sh
      - store_artifacts:
            path: /tmp/artifacts
            destination: ./
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - ./*
            
  publish-github-release:
    docker:
      - image: circleci/golang:1.8
   
    steps:
      - attach_workspace:
          at: /tmp/artifacts

      - run:
          name: "Publish Release on GitHub"
          tag: /(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)/
          command: |
            go get github.com/tcnksm/ghr
            VERSION=1.0.$CIRCLE_BUILD_NUM
            RELEASE=Release1.0.$CIRCLE_BUILD_NUM
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -c $CIRCLE_SHA1 -n $RELEASE $VERSION /tmp/artifacts
           
workflows:
    version: 2
    main:
        jobs:
          - develop-branch:
              filters:
                branches:
                  only: develop
                  
          - master-branch:
              filters:
                branches:
                  only: master
          - publish-github-release:
              requires:
                - master-branch
              filters:
                branches:
                  only: master
